version: '3'
services:
  web:
    build: .
    restart: always
    ports:
     - "1855:80"
    depends_on:
     - postgre
    links:
     - postgre

  postgre:
    image: "postgres:alpine"
    restart: always
    environment:
      POSTGRES_PASSWORD: pgpass
      PGDATA: /data
    volumes:
      - data:/data

volumes:
  data:
